### ISSUE TITLE
Data Source Storage

### ISSUE THREAD

**Issue by awesomepack** [awesomepack/Financial_Dashboard#3]
The transformed dataset needs to be stored using a server connected to the web.

* Azure SQL is a good starting point

**Comment by awesomepack** [comment]
Deploying the finance app through the Django framework provides the architecture to integrate it with a production ready database (such as azure SQL)

**Comment by AbP-sys** [comment]
Submitted a PR integrating the application with Azure SQL. I can keep the server running till the 1st of July, 2023 with my current subscription. You can continue development under your own subscription or reach out to me on [LinkedIn](https://www.linkedin.com/in/abhishek-pagadala/) so that I can give you access to the server I just deployed.

**Comment by awesomepack** [comment]
Hey There. Thanks for configuring the project to handle Azure SQL. I currently can't run my app on the local server for debugging purposes. I imagine because it is now expecting a connection to Azure SQL? If you wouldn't mind, could you point me to the docs / tutorial you used to set up your server? I can use my own subscription. I sent you a connect request on LinkedIn. 
Thanks again for your help.

**Comment by AbP-sys** [comment]
Yes, that's right. You need to some entries in your .env file (which I have mentioned in .env.sample) to run the application. To get those key values, you can follow the steps in _Create Azure SQL Database_ section of [this guide](https://docs.microsoft.com/en-us/samples/azure-samples/azure-sql-db-django/azure-sql-db-django/) from microsoft.

**Comment by awesomepack** [comment]
I was able to run my Django app using an Azure SQL server and database.
