### ISSUE TITLE
Django Migration

### ISSUE THREAD

**Issue by awesomepack** [awesomepack/Financial_Dashboard#5]
Structure the repository so that it follows the architecture of a Django app.

**Comment by AbP-sys** [comment]
I think it would be a good idea to restructure the files such that both the apps (finance_app, Wage_Map) and manage.py are in the base directory of the project instead of /finance_app. I have submitted a PR to get the app running by
`python finance_app/manage.py runserver`

**Comment by awesomepack** [comment]
Hey there AbP-sys,
I pushed a commit where I moved the wage_map and finance_apps to the base directory "Financial_Dashboard"
Thanks for the suggestion. If the structure looks good let me know so I can close this issue.

**Comment by AbP-sys** [comment]
Perfect. Exactly what I had in mind. This just seems more intuitive and easy to work with.
